#!/bin/bash
# MIT License 2025
# Igor Támara <igor.tamara@gmail.com>

if grep -E 'breakpoint()' src/StableHordeForLibreOffice.py >/dev/null; then
  gum log -l error 'Uggghhh! a breakpoint is there'
  return 1
fi

if grep -E '^DEBUG = True$' src/StableHordeForLibreOffice.py >/dev/null; then
  echo "\n   Watch out!!!! We do not want to release with DEBUG=True\n\n"
  echo sed -e \'s/^DEBUG = True$/DEBUG = False/g\' src/StableHordeForLibreOffice.py 
  exit 1
fi

VERSION=$(grep "VERSION = " src/StableHordeForLibreOffice.py | sed -E 's/VERSION = "(.+)"/\1/')

XMLVER=$(grep "version value" oxt/description.xml | sed -E 's/.*"(.*)".*/\1/')
if [ "$VERSION" != "$XMLVER" ]; then
  sed -i -E 's/version value="([0-9]+(\.[0-9]+)*)/version value=\"'$VERSION'/g' oxt/description.xml
  MODVER=$(grep "version value" oxt/description.xml | sed -E 's/.*"(.*)".*/\1/')
  if [ "$VERSION" != "$MODVER" ]; then
    echo "Please review oxt/description.xml and make the version match $VERSION" 
  else
    echo "I just modified the oxt/description.xml , make sure you"
    echo "git add oxt/description.xml; git commit -m \"sync version\""
  fi
  exit 1
fi

CHANGE=$(grep "## \[$VERSION\] - " CHANGELOG.md | sed -E 's/.*\[(.*)].*/\1/')
echo Currently $CHANGE
if [ "$VERSION" != "$CHANGE" ]; then
  echo "hx CHANGELOG.md;git add CHANGELOG.md"
  echo "To update the Changelog"
  exit 1
fi

TAGVER=$(git tag --list | grep "$VERSION")
if [ "$VERSION" != "$TAGVER" ]; then
  echo "git tag $VERSION; git push --tags"
  echo "is what you need"
  exit 1
fi

ADVERTISING=$(grep '"version":' version.json | sed -E 's/.* "(.*)",/\1/')
if [ "$VERSION" != "$ADVERTISING" ]; then
  echo sed -i -E 's/version": ".*"/version": "'$VERSION'"/g' version.json "&& git add version.json && git commit -m \"Rollout version $VERSION\""
  echo "hx version.json"
  echo "to update the advertised version.  It's ok to release, and later advertise"
  RELEASED=$(gh release list -L 1 --json tagName | jq '.[0].tagName' | sed 's/"//g')
  if [ "$VERSION" != "$RELEASED" ]; then
    echo "    Time to:\n"
    echo gh release create "$VERSION" && echo gh release upload "$VERSION" loshd.oxt
  fi
  exit 1
fi


# TODO introspect description.xml

