#!/bin/bash
VERSION=$(grep "VERSION = " src/StableHordeForLibreOffice.py | sed -E 's/VERSION = "(.+)"/\1/')

TAGVER=$(git tag --list | grep "$VERSION")
if [ "$VERSION" != "$TAGVER" ]; then
  echo "git tag $VERSION; git push --tags"
  echo "is what you need"
  exit 1
fi

ADVERTISING=$(grep '"version":' version.json | sed -E 's/.* "(.*)",/\1/')

if [ "$VERSION" != "$ADVERTISING" ]; then
  echo "hx version.json"
  echo "to update the advertised version"
  exit 1
fi

CHANGE=$(grep "## \[$VERSION\] - " CHANGELOG.md | sed -E 's/.*\[(.*)].*/\1/')

echo $CHANGE
if [ "$VERSION" != "$CHANGE" ]; then
  echo "hx CHANGELOG.md;git add CHANGELOG.md"
  echo "To update the Changelog"
  exit 1
fi

# TODO introspect description.xml

echo gh release create "$VERSION" && echo gh release upload "$VERSION" loshd.oxt 
